### ISSUE TITLE
What is the status of the authentication?

### ISSUE THREAD

**Issue by pkit** [voltrondata/flight-sql-server-example#12]
As I can see from the code, the auth implementation uses a mix of "basic" and "bearer" auth with jwt tokens.
Essentially starting with basic and then sending a jwt on the first success and falling back to jwt subsequently.
Is there any spec on that?
As far as I can see, the existing JDBC drivers connect fine, which means they do implement the same protocol. Do they?
Probably they can get away with always using basic?
Issuing 10 hour jwt tokens looks fishy too but that's probably just an example.
btw, is TLS required?

**Comment by prmoore77** [comment]
> So, there's no spec? :)
> 
> In my experience databases usually have their own credential management. Thus all that "bolt on" auth is rarely useful.
> 
> Anyway, my goal is to implement FlightSQL interfaces for ClickHouse.
> 
> 1. Expose ClickHouse as a FlightSQL server.
> 2. Add a table function/storage engine to ClickHouse that can talk to other Flight/FlightSQL servers.
> 
> So far for ClickHouse, as a real database, none of the "helper" functions in `FlightSqlServerBase` are really useful. And it looks like I will need to go one level deeper, into the actual grpc server/service/transport layer, to implement all the needed hooks.

I'm not aware of a standard spec for security for Flight SQL.  As you said, I think it depends on the underlying Database engines.  In the case of DuckDB and SQLite (the engines used in this solution) - there is no auth at all - so this Flight SQL solution actually adds security.

If you are writing a Flight SQL Server solution for a database engine (such as ClickHouse) which has authentication built-in security - I think you'll have to research how best to implement security for Flight SQL in such a case.  I haven't yet attempted that...

**Comment by prmoore77** [comment]
Part of my motivation for adding an auth layer for this example was this issue I opened in the DuckDB repo: https://github.com/duckdb/duckdb/issues/2519

**Comment by prmoore77** [comment]
> Hmm, another interesting question is why AuthHandler is not used and is set to NoOp? It looks like `AuthHandler.incoming_headers()` should get you the functionality of `HeaderAuthServerMiddlewareFactory` for free. But maybe it doesn't?

Good point!  I had missed this.  I will attempt to build a branch using the built-in auth-handler to see if it functions the same or better.  Thanks for pointing it out...
