### ISSUE TITLE
Attempt to use Arrow Flight's built-in AuthHandler class instead of custom middleware for authentication

### ISSUE THREAD

**Issue by prmoore77** [voltrondata/flight-sql-server-example#16]
The current authentication functionality of the example Flight SQL Server relies on customized middleware that handles `basic` and `bearer` token authentication.

The built-in functionality of Arrow Flight's [ServerAuthHandler class](https://github.com/apache/arrow/blob/596259ee47b5c675b71432743d9bfd196efe08e3/cpp/src/arrow/flight/server_auth.h#L54C27-L54C44) should handle this for us.  We should attempt to switch to built-in Arrow functionality to reduce the code footprint as well as to improve performance and security of the authentication.

This was pointed out by: @pkit

**Comment by pkit** [comment]
Nice, thank you!

**Comment by prmoore77** [comment]
Hey @pkit - I had attempted to use the built-in AuthHandler class, but ultimately found it was incompatible with the Arrow Flight SQL JDBC driver.  I had to revert to the middleware solution...

I believe that the built-in class is designed for Flight RPC clients, not Flight SQL clients...
