### ISSUE TITLE
Deploy flight sql server in GCP Cloud Run

### ISSUE THREAD

**Issue by LeonBamRazor** [voltrondata/flight-sql-server-example#17]
Hello, 
thanks for sharing this.  I was looking for example like this, and  I wonder is there there are any guidelines to deploy this at CloudRun at GCP. CloudRun supports grpc endpoints and I am not sure what is the correct call from adbc_driver_flightsql url and port. Hope you can share this. thanks

**Comment by prmoore77** [comment]
hey @LeonBamRazor - I've never run this in GCP CloudRun before, but have run it in Kubernetes with some good success (with both x86 and arm).  We may release a helm chart in the future to make it easy for folks to do the same.  I'll look into CloudRun to see if that is a viable option for this...

**Comment by LeonBamRazor** [comment]
Thanks, @prmoore77 for looking into it.
They have some way to support streaming and grpc (they are google...).
I understand that you focus on k8s, but Cloud Run can be really nice ability so just to deploy a serverless flight-sql server
