### ISSUE TITLE
Error while opening a view in DBeaver

### ISSUE THREAD

**Issue by thinkORo** [voltrondata/flight-sql-server-example#2]
First of all, thank you very much for this examplary implementation.

I use the Docker image as described with a DuckDB database with version 0.8.1.

I have created a database connection in DBeaver. And a view there for testing.

If I now open this view in DBeaver Navigation, I get the following error message: Cannot invoke "cfjd.org.apache.arrow.vector.VarBinaryVector.get(int)" because "schemaVector" is null

To be on the safe side, I have also created a table, and the behaviour is the same here too.

Screenshot

![Screenshot_2023-06-26_09-14-11 - Arrow Flight Server with DBeaver](https://github.com/voltrondata/flight-sql-server-example/assets/10477663/3ed8ac21-0943-4158-a7cb-b298f5f71cec)

**Comment by prmoore77** [comment]
hi @thinkORo - thanks for submitting the issue!  We will try to take a look and see if we can fix!

**Comment by thinkORo** [comment]
Hi @prmoore77, thank you.

**Comment by prmoore77** [comment]
Hi @thinkORo - this should now be fixed in the code.  The Github Actions pipeline is now running, and should publish the image to DockerHub this evening (see: https://github.com/voltrondata/flight-sql-server-example/actions/runs/5557952486)
