### ISSUE TITLE
"docker build" runs into an error

### ISSUE THREAD

**Issue by thinkORo** [voltrondata/flight-sql-server-example#23]
To try out a minor change to the code (I would like to define the user as well as the password), I thought I would build a new Docker image. (Hint: Im running on Arch linux and build the binary if I'd follow the instruction in "Option 2 - Steps to build the solution manually")

However, when I run a "docker build", I get the following error message:

```
[8/8] Completed 'jwt_cpp_project'
-- Found Boost: /lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: program_options 
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/flight_sql/build
CMake Error: The source directory "/opt/flight_sql/build/install" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
The command '/bin/sh -c mkdir build &&     cd build &&     cmake .. -GNinja -DCMAKE_PREFIX_PATH=${ARROW_HOME}/lib/cmake -DCMAKE_INSTALL_PREFIX=/usr/local &&     cmake install' returned a non-zero code: 1
```

Am I doing something wrong or do I need to set special environment variables?

**Comment by prmoore77** [comment]
Hi @thinkORo - I'll look at the Docker build issue.  In the meantime, I just recently updated the codebase to let you specify the user and password - have you tried the latest release?

**Comment by thinkORo** [comment]
Hi @prmoore77 

unfortunately the latest Docker Image doesn't work for me any longer.

I use "INIT_SQL_COMMANDS" to set my S3 properties and get this "error":

```
Running Init SQL command:
 SET s3_endpoint='myS3Server:9199';
Error: Invalid: Catalog Error: Setting with name "s3_endpoint" is not in the catalog, but it exists in the httpfs extension.
```

With Version 0.1.4 this wasn't or isn't an issue.
