### ISSUE TITLE
Add Makefile

### ISSUE THREAD

**Issue by rupurt** [voltrondata/flight-sql-server-example#5]
How do you feel about adding a `Makefile` which abstracts away the steps of building the project?

That would also make it easier to package with something like Nix.

**Comment by prmoore77** [comment]
hi @rupurt - I think this is a great idea.  I'm not an experienced C++ developer by any means, so making this better is definitely welcome.  Contributions are welcome if you have an idea on how to get started.  I'll research it also in the meantime...

**Comment by rupurt** [comment]
I've been taking a crack at it based on my DuckDB experience but I'm only new to C++ so it'll take me a while :smile:
