### ISSUE TITLE
Add shared library build

### ISSUE THREAD

**Issue by rupurt** [voltrondata/flight-sql-server-example#6]
How do you feel about adding a build which would allow the server to be used as a shared library?

That would allow the core of the project to be embedded in other C ABI compatible languages like C/C++/Rust/Zig etc...

**Comment by prmoore77** [comment]
Hi @rupurt - Thanks for opening the issue!  Could you elaborate a little more on this?  How do you envision an embedded version of this Flight SQL server implementation being used by those languages?

**Comment by rupurt** [comment]
Something similar to DuckDB where I can embed the flight server within a larger application and give it a CLI interface. In my ideal world the `Makefile` would be able to build something like `libflightsqlserver.so` and I would be able to link against that and create instances of the server.

**Comment by prmoore77** [comment]
hey @rupurt - I've attempted to build a shared library - please see: https://github.com/voltrondata/flight-sql-server-example/tree/feature/library.  Any feedback would be appreciated...
