### ISSUE TITLE
[Feature Request] New "docker run" parameter for session initialization

### ISSUE THREAD

**Issue by thinkORo** [voltrondata/flight-sql-server-example#7]
First of all, this is not a bug, but a feature request.

To access data via DuckDB in S3 for example, I need to execute certain SQL statements for each session, like:

- INSTALL httpfs
- LOAD httpfs
- SET s3_region='us-east-1'
- and others

It would be very nice if I could define some parameters via "docker run" that would then be executed against DuckDB for each "arrow flight" session.

For example:
```
docker run --name flight-sql \
           --env SESSION_INIT="INSTALL httpfs"
           --env SESSION_INIT="LOAD httpfs"
           --env ...
```

**Comment by thinkORo** [comment]
Hi @prmoore77 

thank you very much for your support and implementation. It works like a charm.

Oliver

**Comment by prmoore77** [comment]
> Hi @prmoore77 
> 
> 
> 
> thank you very much for your support and implementation. It works like a charm.
> 
> 
> 
> Oliver

Thanks for testing it!
